name: Update AI Dataset

on:
  workflow_dispatch:        # enables the "Run workflow" button
  schedule:
    - cron: "0 3 * * *"     # daily at 03:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # allow the job to commit back to the repo
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml pandas

      - name: Run update script
        run: python update_dataset.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add dataset.csv
          git commit -m "Update dataset [skip ci]" || echo "No changes to commit"
          git push
