name: Update AI Dataset

on:
  workflow_dispatch:         # manual run button
  schedule:
    - cron: "0 3 * * *"      # daily at 03:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # allow commits back to the repo

    env:                      # make secrets available to the script
      SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
      SHOPIFY_ADMIN_API_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_TOKEN }}
      STORE_FRONT_URL: https://www.malegroomingsupplies.com
      API_VERSION: 2024-07

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: python update_dataset.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ai-dataset.json
          git commit -m "Update ai-dataset.json [skip ci]" || echo "No changes to commit"
          git push
